// Array de 100 palabras para el SearchBar
export const words = [
  'Laptop HP Pavilion',
  'Teclado mecánico RGB',
  'Monitor 24 pulgadas Full HD',
  'Mouse inalámbrico Logitech',
  'Tarjeta gráfica NVIDIA GeForce RTX 3070',
  'Disco duro SSD 1TB',
  'Memoria RAM DDR4 16GB',
  'Procesador AMD Ryzen 5 5600X',
  'Placa base ASUS ROG Strix B550',
  'Auriculares gamer con micrófono',
  'Impresora multifunción Epson EcoTank',
  'Router Wi-Fi 6 de doble banda',
  'Altavoces estéreo Bluetooth',
  'Cámara web HD 1080p',
  'Tarjeta de sonido externa USB',
  'Mochila para laptop resistente al agua',
  'Silla gamer ergonómica',
  'Escritorio para computadora con soporte para monitor dual',
  'Hub USB con múltiples puertos',
  'Tableta gráfica Wacom Intuos',
  'Cable HDMI de alta velocidad 4K',
  'Fuente de poder 750W certificada 80 Plus Gold',
  'Refrigeración líquida para CPU',
  'Lector de tarjetas de memoria USB 3.0',
  'Kit de limpieza para pantalla LCD',
  'Alfombrilla para mouse de gran tamaño',
  'Adaptador Bluetooth 5.0 para PC',
  'Batería externa para laptop',
  'Soporte ajustable para laptop',
  'Luz LED RGB para escritorio',
  'Monitor curvo ultrawide 34 pulgadas',
  'Webcam con obturador de privacidad',
  'Teclado inalámbrico compacto',
  'Módulo de memoria RGB Corsair Vengeance',
  'Tarjeta de captura de video 4K',
  'Hub Ethernet USB-C',
  'Caja de herramientas para reparación de computadoras',
  'Funda resistente para laptop',
  'Filtro de luz azul para pantalla',
  'Estación de carga USB con soporte para teléfono',
  'Sistema de altavoces 5.1 para PC',
  'Micrófono USB de condensador',
  'Tarjeta de red Wi-Fi PCIe',
  'Candado de seguridad para laptop',
  'Caja para almacenamiento de discos duros',
  'Alicate para cables de red',
  'Kit de tornillos para ensamblar PC',
  'Mini proyector portátil',
  'Adaptador de corriente universal para viajes',
  'Base de refrigeración para laptop',
  'Lámpara LED de escritorio con puerto USB',
  'Pendrive USB 3.0 de 128GB',
  'Estación de trabajo ajustable en altura',
  'Almohadilla para muñeca ergonómica',
  'Kit de limpieza de aire comprimido',
  'Control remoto para presentaciones',
  'Cable de extensión USB 2.0',
  'Soporte para auriculares RGB',
  'Hub USB con lector de tarjetas SD',
  'Teclado numérico externo',
  'Kit de herramientas de precisión',
  'Adaptador HDMI a VGA',
  'Organizador de cables para escritorio',
  'Sistema de sonido envolvente para PC',
  'Cable de seguridad para laptop',
  'Bolsa de transporte para laptop',
  'Funda antideslizante para mouse',
  'Auriculares inalámbricos con cancelación de ruido',
  'Soporte para tablet ajustable',
  'Estación de carga inalámbrica para teléfono',
  'Base para laptop con ventiladores',
  'Hub USB-C con salida HDMI',
  'Mesa plegable para laptop',
  'Mousepad con carga inalámbrica',
  'Cable DisplayPort 1.4',
  'Teclado ergonómico dividido',
  'Auriculares con micrófono desmontable',
  'Monitor táctil de 22 pulgadas',
  'Hub USB-C con lector de tarjetas microSD',
  'Alfombrilla de gel para mouse',
  'Hub USB 3.0 con interruptores individuales',
  'Soporte para monitor con cajón',
  'Cable de alimentación para PC',
  'Organizador de cables magnético',
  'Auriculares deportivos con resistencia al agua',
  'Soporte para laptop ajustable en ángulo',
  'Funda rígida para disco duro externo',
  'Barra de sonido USB para computadora',
  'Kit de expansión de almacenamiento NAS',
  'Adaptador USB-C a Ethernet',
  'Soporte para tablet y teléfono',
  'Alfombrilla de ratón RGB con carga inalámbrica',
  'Cable de audio estéreo de 3.5 mm',
  'Kit de seguridad para cámara web',
  'Base de carga vertical para laptop',
  'Funda para teclado mecánico',
  'Lápiz óptico para tabletas gráficas',
  'Teclado mecánico retroiluminado',
  'Tarjeta gráfica AMD Radeon RX 6800 XT',
  'Disco duro externo de 2TB',
  'Memoria RAM DDR4 32GB (2x16GB)',
  'Procesador Intel Core i9-11900K',
  'Placa base MSI MPG B550 Gaming Edge WiFi',
  'Auriculares inalámbricos con cancelación de ruido',
  'Impresora láser monocromática',
  'Router mesh para toda la casa',
  'Altavoces 2.1 con subwoofer',
  'Webcam 4K con seguimiento facial',
  'Mochila para laptop antirrobo',
  'Silla ergonómica de oficina',
  'Hub USB-C con múltiples puertos y lector de tarjetas',
  'Refrigeración por aire para CPU',
  'Lector de huellas dactilares USB',
  'Cable Thunderbolt 3 de 2 metros',
  'Monitor OLED 4K HDR de 32 pulgadas',
  'Teclado plegable Bluetooth',
  'Mouse ergonómico vertical',
  'Tarjeta de sonido externa USB-C',
  'Estación de acoplamiento para laptop',
  'Micrófono de condensador USB para streaming',
  'Soporte para monitor ajustable en altura',
  'Adaptador HDMI inalámbrico',
  'Disco duro SSD externo resistente al agua',
  'Estabilizador de corriente para PC',
  'Kit de limpieza de componentes electrónicos',
  'Base de carga para auriculares inalámbricos',
  'Soporte para tablet y lápiz',
  'Sistema de iluminación inteligente para escritorio',
  'Hub USB 3.0 con interruptores individuales y carga rápida',
  'Cámara de seguridad para el hogar con detección de movimiento',
  'Cable VGA de alta resolución',
  'Soporte para micrófono de escritorio',
  'Tarjeta de expansión PCIe USB 3.1 Gen 2',
  'Filtro de privacidad para pantalla de laptop',
  'Funda para tablet resistente',
  'Lector de tarjetas inteligentes USB',
  'Teclado mecánico compacto tenkeyless',
  'Mousepad con carga inalámbrica integrada',
  'Cable de extensión USB 3.0 de 3 metros',
  'Luz de escritorio LED regulable',
  'Tarjeta de red inalámbrica USB 5G',
  'Candado de seguridad para monitor',
  'Bolsa de transporte para accesorios de computadora',
  'Base de refrigeración para consola de juegos',
  'Estación de carga para controladores de consola',
  'Auriculares con iluminación RGB',
  'Soporte para laptop con ventilador de refrigeración',
  'Hub USB-C con salida VGA',
  'Mesa de escritorio plegable',
  'Mouse inalámbrico recargable',
  'Cable HDMI 2.1 de 5 metros',
  'Teclado silencioso para oficina',
  'Adaptador de corriente universal para laptop',
  'Organizador de cables magnético',
  'Hub USB-C con lector de tarjetas CFexpress',
  'Auriculares con sonido envolvente 7.1',
  'Funda para disco duro externo',
  'Barra de sonido Bluetooth para PC',
  'Kit de expansión de almacenamiento RAID',
  'Adaptador USB-C a HDMI y Ethernet',
  'Soporte para tablet con carga inalámbrica',
  'Alfombrilla de ratón XXL para gaming',
  'Cable de audio óptico Toslink',
  'Kit de seguridad para laptop con alarma',
  'Base de carga vertical para tablet',
  'Funda para teclado y mouse',
  'Lápiz táctil para tabletas capacitivas',
  'Ventilador USB portátil',
  'Base refrigeradora para laptop gaming',
  'Hub USB 3.0 con interruptores individuales y display OLED',
  'Cable DisplayPort 1.4 de 3 metros',
  'Teclado inalámbrico plegable',
  'Auriculares deportivos inalámbricos',
  'Monitor táctil de 27 pulgadas',
  'Hub USB-C con lector de tarjetas XD',
  'Alfombrilla de ratón con carga solar',
  'Hub USB 2.0 con forma de robot',
  'Soporte para monitor con altavoces integrados',
  'Cable de alimentación para monitor',
  'Organizador de cables en espiral',
  'Auriculares con micrófono desmontable y luz LED',
  'Soporte para laptop con lámpara LED integrada',
  'Funda rígida para teclado mecánico',
  'Lápiz óptico para pantallas táctiles',
  'Mini PC con procesador Intel Core i5',
  'Teclado inalámbrico retroiluminado',
  'Mouse gamer con sensor óptico de alta precisión',
  'Monitor ultrawide curvo de 34 pulgadas',
  'Impresora 3D de alta resolución',
  'Auriculares con cancelación de ruido y Bluetooth',
  'Router gaming con tecnología WiFi 6E',
  'Disco duro externo SSD resistente a golpes',
  'Memoria RAM RGB DDR4 32GB (2x16GB)',
  'Procesador AMD Ryzen 9 5900X',
  'Placa base Gigabyte Aorus X570',
  'Webcam con reconocimiento facial',
  'Silla gaming con masajeador integrado',
  'Teclado mecánico para iPad Pro',
  'Mouse ergonómico vertical inalámbrico',
  'Tarjeta gráfica externa para laptops',
  'Auriculares con sonido envolvente Dolby Atmos',
  'Impresora fotográfica portátil',
  'Router de doble banda con sistema de malla',
  'Altavoces Bluetooth impermeables',
  'Micrófono de estudio USB de condensador',
  'Cámara de seguridad para escritorio',
  'Hub USB-C con carga inalámbrica',
  'Refrigeración líquida RGB para CPU',
  'Lector de tarjetas magnéticas USB',
  'Cable DisplayPort 1.4 de 5 metros',
  'Funda para laptop con diseño personalizado',
  'Estación de carga para baterías recargables',
  'Adaptador HDMI a DisplayPort',
  'Soporte para micrófono de estudio',
  'Hub USB 3.0 con interruptor de encendido y apagado',
  'Cable USB magnético para carga rápida',
  'Funda resistente para tablet con soporte',
  'Teclado mecánico inalámbrico compacto',
  'Mousepad con carga inalámbrica y RGB',
  'Cable HDMI 2.1 de 3 metros con Ethernet',
  'Lámpara de escritorio inteligente',
  'Tarjeta de sonido externa USB 7.1',
  'Mesa de escritorio con altura ajustable',
  'Mouse inalámbrico silencioso',
  'Cable VGA de alta calidad con filtros',
  'Teclado plegable con touchpad',
  'Hub USB-C con puerto HDMI y Ethernet',
  'Auriculares inalámbricos con luz LED',
  'Soporte para laptop con ventiladores silenciosos',
  'Hub USB 3.0 con lector de tarjetas SIM',
  'Estación de carga rápida para dispositivos móviles',
  'Base de refrigeración para consolas de juego',
  'Adaptador de corriente para automóvil USB-C',
  'Organizador de cables magnético con etiquetas',
  'Hub USB-C con salida de video 8K',
  'Auriculares con micrófono desmontable y cancelación de ruido',
  'Soporte para tablet con brazo ajustable',
  'Cable de extensión USB 3.1 de 2 metros',
  'Luz LED inteligente con control por voz',
  'Base de carga para baterías de consola',
  'Hub USB 2.0 con diseño retro de cassette',
  'Mesa de escritorio plegable con ruedas',
  'Mouse inalámbrico ergonómico para viajes',
  'Cable de alimentación con enchufe retráctil',
  'Organizador de cables en espiral de silicona',
  'Base de carga vertical para laptop',
  'Funda rígida para mouse y accesorios',
  'Lápiz táctil con funciones personalizables',
  'Ventilador USB de cuello ajustable',
  'Hub USB-C con lector de tarjetas NFC',
  'Alfombrilla de ratón con reposamuñecas de gel',
  'Hub USB 3.0 con puerto de carga rápida',
  'Cable DisplayPort 1.4 de 1 metro',
  'Teclado mecánico con teclas personalizables',
  'Auriculares deportivos inalámbricos resistentes al agua',
  'Monitor táctil de 22 pulgadas con soporte ajustable',
  'Hub USB-C con HDMI y carga inalámbrica',
  'Alfombrilla de ratón con luz RGB programable',
  'Soporte para monitor con cajón organizador',
  'Cable de alimentación con interruptor de encendido y apagado',
  'Organizador de cables magnético de escritorio',
  'Auriculares con micrófono desmontable y diadema ajustable',
  'Soporte para laptop con enfriamiento activo',
  'Funda rígida para teclado y mouse',
  'Lápiz óptico recargable para tabletas capacitivas',
];
